name: Dependency Review
on: [pull_request_target]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4
        with:
          comment-summary-in-pr: always
          allow-licenses: MIT, Apache-2.0, ISC, BSD-2-Clause, BSD-3-Clause
